### ISSUE TITLE
Layers are not shown / different behaviour between first and following openings of projects / svg-problems

### ISSUE THREAD

**Issue by koenigherford** [opengisch/QField#130]
qfield 0.9.10 (and  qgis2compat 0.4.6. and qfieldsync 1.0.0 and qgis 2.18.7) / android 5.0.2 (Samsung Tab A) /5.0.1 (Galaxy S4):

I'm trying to export a project with data stored in a postgresql-database to a mobile device with the export-setting "offline-editing" ("no- action" was default-setting)
1)
The sample-original-project only contains 1 polygon-layer. 
The qfieldsync-generated project can be opened in qgis-desktop 2.18.7 without problems. On the mobile device the screen result is as expected on the **first** opening of the project. After  some zooming and paning - nothing else -an closing qfield and **restarting** it with the same  project the map screen remains blank (no busy-circle in the right corner). The layer is shown in the layer-list with its categorized symbology.  If you copy the "blank" project to another android mobile device its map blank there too. In qgis the "blank" project can be opened normally.
The exported projects to this sub-issue #1 before first opening and after first opening can be downloaded here:
https://databox0230.krz.de/#/public/shares-downloads/HeyKIsX8b9Of1kehgWuGfOd2Rb4U6dLE

2)
Using other-more complicated projects with more (30-40) layers some layers and svg-symbology some layers have the same behavior - others are shown. The svg-symbology seems to be lost -the map is crowded with "?"-symbols.  The identify-bar on the right side of the screen is pre-activated. This identify-bar can not be exited by tapping any button of the mobile device.

![grafik](https://cloud.githubusercontent.com/assets/28433436/25739701/501d798a-3183-11e7-9df0-0b41bea06dc6.png)

After trying to restart qfield it goes on hold immediately in the opening-process. So you have  to remove the project from your device to start qfield again and you cann not use the project.

(The download-link for the exported projects to sub-issue #2 before first opening and after first opening will be send to you directly.)

As there is a different behaviour with the project in first and the follwing openings it seems qfield changes the project file.

3)
Opening "about" in your menu and trying to go back to main menu by the "back"-button of the mobile device qfield quits immediately completely.

4)
It would be nice to have a possibility to change the export options of several layers together by one click instead of having to change the options layer by layer.

The problems #1 und #2 were not discovered before

**Comment by koenigherford** [comment]
It seems that there is a problem with the "map-themes" in the export-process of qfieldsync. With another project - that only contained 2 layers- both layers were displayed and could be switched on/off normally on qgis 2.18.7 desktop in the qfield-exported project until I used the map-theme-function first time. From then on the layer, which should be visible by theme-definition, could not be seen any longer on the map altrough visibility was activated. There was no possibility to change this behaviour by manually checking/unchecking the layer. The attribute table said that data was still there and "zoom on object" gave no other results.

**Comment by koenigherford** [comment]
I've exported all the data from the project from the postgresql-datasource to a spatialiite-database manually. Then changed the datasource of the layers to the new spatialite database and copied this (modified) project with the the new spatialite-database to the mobile device (and copied the custom svg's to….\Tablet\Android\data\ch.opengis.qfield\files\share\svg - this path is **not** shown in about -menu) and everything worked fine. So it seems it's no problem of the data(-stucture)

**Comment by signedav** [comment]
Hi @koenigherford - I think this is solved with this implementation #266 
Can you confirm?

**Comment by koenigherford** [comment]
I'm very happy to see the issue #266 / part of #130 (4c  - pressing back-key to close sidebar) is solved with qfield 0.10.13. 
The issue with rule based-layers (4d - deactivated visibility of rules on second start) also seems to be solved by export from qgis 3.0. 
Thank you very much for your efforts !!!
The SVG-files are still not recognized and displayed with "?" in map. The "settings/about"-path is still empty.

**Comment by signedav** [comment]
Thanks for feedback @koenigherford 

I just excluded the issues #271 and #272 from this one. Could you please give more information - especially about the problem with svg-symbols?

**Comment by koenigherford** [comment]
…dancing in my office with joy !

Made a fresh install of qfield 0.10.13 with a qgis3-exported project on an new device and everything worked as expected  - SVG's are shown too !!!

Then took two older devices with the described issues (I think I checked positive, whether the custom svg-folders existed or not). I completely uninstalled the qfield-app an made a new install, copied the custom-svg-folders to the device and everything worked too. The other devices with qfield were out in the field and I didn't have access - I'll try tomorrow to check the reason for our problems: I'm not sure whether the issue has a reason in updating over an existing qfield-version.

1)
Maybe the complete \Android\data\ch.opengis.qfield\files\share\svg -folder (with it's  default- and custom-svg-data-subfolders) is deleted during the update-process. In this case after the update the custom-svg-folders will be missing and displayed (I thought to have checked, if the folders are existing in the shared folders - but  will double-check on other devices tomorrow). In your documentation (http://www.qfield.org/docs/project-management/android-data-structure.html) you recommend not to store project data in /Android/data/ch.opengis.qfield/files -folder because  of risks of loss of data in cases of UNINSTALLATION. Maybe in cases of UPDATES the folder is affected too. But storing the custom svg-symbols in the … ch.opengis.qfield\files\subfolders is strongly recommended and in cases of updates will be likely a svg-data-loss.


In this case you may add a special warning to your documentation to recopy the custom-svg-data to device or the user may use an external data-folder which is not affected in update processes. In cases of an update the qfield remembers the last opened project - so it may be possible to preserve custom additional/external(sd-card..) (svg-…) path-settings during update-process.

2)
Maybe we had other problems - something went wrong with the settings during the update-process and although the custom-folders were preserved but are not recognized…

However - we are very glad to have our devices with working projects in the field now - Thank you very much for your efforts !!!

Mit freundlichen Grüßen

Ralf König


Sehr geehrter Herr Freese,
ich werde morgen versuchen, noch an ein paar anderen Geräten die Ursache im Detail zu finden. Sagen Sie mir Bescheid wann es klappt.
Mit freundlichen Grüßen

Ralf König


[cid:image002.gif@01D3DBEE.B4A862F0]
Von: signedav [mailto:notifications@github.com]
Gesendet: Dienstag, 24. April 2018 15:16
An: opengisch/QField
Cc: König, Ralf (Hansestadt Herford); Mention
Betreff: Re: [opengisch/QField] Layers are not shown / different behaviour between first and following openings of projects / svg-problems (#130)


Thanks for feedback @koenigherford<https://github.com/koenigherford>

I just excluded the issues #271<https://github.com/opengisch/QField/issues/271> and #272<https://github.com/opengisch/QField/issues/272> from this one. Could you please give more information - especially about the problem with svg-symbols?

**Comment by signedav** [comment]
Thanks for the feedback @koenigherford So I'll close the issue with the svg and let the path-information in the about-dialog still open.

**Comment by koenigherford** [comment]
made an update on a another device - everything with the svg's worked well

Mit freundlichen Grüßen

Ralf König
Abteilung Stadtplanung, Grünflächen und Geodaten
[cid:image001.jpg@01D3DC62.096499D0]<http://www.herford.de/>
Tel.: +49 5221 189 617
Fax: +49 5221 189 691
eMail: Ralf.Koenig@Herford.de<mailto:Ralf.Koenig@Herford.de>

Hansestadt Herford
Auf der Freiheit 21
32052 Herford
http://www.herford.de

Bitte denken Sie an Ihre Verantwortung gegenüber der Umwelt, bevor Sie die E-Mail ausdrucken.

[cid:image002.gif@01D3DC62.096499D0]
Von: signedav [mailto:notifications@github.com]
Gesendet: Dienstag, 24. April 2018 18:05
An: opengisch/QField
Cc: König, Ralf (Hansestadt Herford); Mention
Betreff: Re: [opengisch/QField] Layers are not shown / different behaviour between first and following openings of projects / svg-problems (#130)


Thanks for the feedback @koenigherford<https://github.com/koenigherford> So I'll close the issue with the svg and let the path-information in the about-dialog still open.
