### ISSUE TITLE
Crash on 32 bit devices with QField bigger 1.5.3

### ISSUE THREAD

**Issue by gispro168** [opengisch/QField#1328]
Hello,

I have GNSS controller (https://tersus-gnss.com/product/tc20-controller) with the following specifications:
Rugged smart phone 4.3’’ display
4G GSM unlocked Android 6.0
Quad-Core 1.3GHz CPU
2GB RAM + 16GB ROM

However, it is always crashed when trying to run latest beta QField 1.7. What could be the issue?

Thanks

**Comment by grdaveygrd** [comment]
Hello,

QField has crashed on my device for several updates and I am disappointingly stuck on V 1.5.3. The device is a 32bit Samsung Galaxy Tab S2 with Android 7. I might be having the same problems as you.

**Comment by signedav** [comment]
Thanks for reporting.  It's not about Android 6.0 - it's about 32 bit devices.

This is a known issue. See the explanation in the[ blog post of the last release 1.6](https://www.opengis.ch/de/2020/08/18/qfield-1-6-is-out/):
> Unfortunately, we are experiencing a crash on startup with 32 bit devices. These devices are not that common any more, but if you have a device that is already a couple of years old it’s very well possible that it comes with a 32 bit cpu builtin. Despite the team’s hard efforts to isolate the reason, we were not able to find out what it was yet. Because of this we will not be able to update to 1.6 for these devices at the moment. We still hope that we will find a solution for this but don’t know yet when this will be.

As far as I know we had a lead to a solution and that's why we pushed it with 1.7. to beta (in the official release it's still 1.5.3 for 32 devices) but obviously it's not fixed.

**Comment by grdaveygrd** [comment]
I just upgraded to QField 1.7.2 on my 32 bit tablet and it is now working, doesn't crash on start up. But it does crash with labels enabled.

**Comment by signedav** [comment]
Okay @grdaveygrd 

@gispro168 can you confirm, that there is no crash anymore on startup with 1.7.2 (or 1.7.3)?
If so, we can close this issue and continue here #1329

**Comment by grdaveygrd** [comment]
Yes I can confirm no crash on start up with either of these versions. Thanks very much. But there is still a problem with labels. When I open a project with labels enabled, it doesn't initially crash. But if I scroll around, it crashes immediately.

**Comment by signedav** [comment]
Thanks. So we close this, since the labeling crash is considered here #1329
