### ISSUE TITLE
Unable to load wms layers with newer windows build 

### ISSUE THREAD

**Issue by lomptorne** [opengisch/QField#2136]
Hello,

Since a recent Windows's build Qfield seems unable to load wms map layers(or at least the one I want to load). 
It still work flawlessly with a previous build, but not with the current one available at opengis.ch. 

don't hesitate to ask for more infos. 
Thanks you in advance for your concerns. 

**QField version:** [works on : "local-dev"(4499e2)  - Do not work on : "local-dev"(265431) ]

## Additional information:

* Problem started happening recently, didn't happen in an older version of QField: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by nirvn** [comment]
@m-kuhn , this was fixed right? I remember us discussing the missing provider plugins.

**Comment by m-kuhn** [comment]
It's an open documentation issue, see here https://github.com/opengisch/QField-docs/issues/138

**Comment by m-kuhn** [comment]
The builds are correct, but the link on the documentation is broken. See https://github.com/opengisch/QField-docs/issues/138


Would be nice if someone could fix the docs there.

**Comment by lomptorne** [comment]
Hello,

Still have the problem with the lastest Build. 
Not on a previous one. 

Thank you, kind regards, 
![image](https://user-images.githubusercontent.com/61391570/135811766-4754a1db-83f3-48ba-9cf4-88dd04344629.png)

**Comment by m-kuhn** [comment]
Hi @lomptorne where did you download this from exactly?

**Comment by lomptorne** [comment]
Hello M. Kuhn, 

On your website at this link this morning.

https://qfield.org/docs/fr/install/index.html

Thanks you, kind regards.

**Comment by m-kuhn** [comment]
Indeed it's broken again.

**Comment by nirvn** [comment]
Fixed by https://github.com/opengisch/QField/pull/2197 -- 

@lomptorne , the next set of builds will fix this, in the meantime you can grab a working build artifact here (https://github.com/opengisch/QField/actions/runs/1307100692)

**Comment by lomptorne** [comment]
Thank you for the quick fix, I've kept and old working version in the meanwhile.
