### ISSUE TITLE
mm in Scalebar

### ISSUE THREAD

**Issue by signedav** [opengisch/QField#273]
The Scalebar displays mm as measure. If this should be meters instead or there is something wrong with the coordinate system of the project I need to check.
![whatsapp image 2018-04-24 at 18 17 16](https://user-images.githubusercontent.com/28384354/39200254-f05b2224-47eb-11e8-8002-257bd35cb5dd.jpeg)

Or checkout the QgisQuick implementation of the scalebar.

**Comment by signedav** [comment]
Issue is, that it expects:
```
QString QgsUnitTypes::toAbbreviatedString( QgsUnitTypes::DistanceUnit unit )
```
instead of:
```
QString QgsUnitTypes::toAbbreviatedString( QgsUnitTypes::LayoutUnit unit )
```
And while: 
```
    //! Layout measurement units
    enum LayoutUnit
    {
      LayoutMillimeters = 0, //!< Millimeter
```
has other values than:
```
    //! Units of distance
    enum DistanceUnit
    {
      DistanceMeters = 0, //!< Meters
```

I belief this is solved with newer QGIS.

**Comment by signedav** [comment]
Just found QGIS update PR #295

**Comment by m-kuhn** [comment]
Does the update fix it?

**Comment by signedav** [comment]
Just tried. No, it doesn't. But not sure if it's the update that does not work or the issue still exists in the updated version (should not).

**Comment by ElvisDahnert** [comment]
Hello
This problem persists.
The scale bar still shows **mm**, but the measure tool shows the correct unit (**m**).

![Screenshot_20191108-091355-2](https://user-images.githubusercontent.com/48390608/68478351-66759100-020e-11ea-9f1e-2fa644c7003f.png)

![Screenshot_20191108-093604](https://user-images.githubusercontent.com/48390608/68478352-66759100-020e-11ea-912c-f6f6c2c1b2ff.png)

Thanks.

**Comment by signedav** [comment]
@3nids Do you have an idea about that? 
The fix has been removed when we started using the QgisQuickMapSettings here https://github.com/opengisch/QField/commit/4caecfe3538e79d19f6e6e12b84cd882140d502f#diff-f8aabe81c74600fdc680277f6a5f4028

**Comment by 3nids** [comment]
This was introduced by the new Osgeo4A SDK.
There were two methods with the same name being invokable.
PR here https://github.com/qgis/QGIS/pull/33247
Once merged, we need to build a new SDK.

**Comment by signedav** [comment]
Okay, thanks.

**Comment by nirvn** [comment]
Long gone.
