### ISSUE TITLE
WMS provider not working on Android Qfield only

### ISSUE THREAD

**Issue by ItaliaMetal** [opengisch/QField#4243]
### Describe the issue
I'm having issues on showing maps from a WMS provider, only on the Android version of QFIELD 2.7.6. 

### Reproduction steps
I created a test project on Qgis 3.28.3 Firenze with some WMS providers, in QGIS  and  in Qfield version 2.6.3 for Windows 10 (64bit) it works fine, when I load it  in Qfield for Android ver 2.7.6 it loads all WMS maps except the ones  coming from this WMS provider https://sit.cittametropolitana.na.it/geoserver/raster/ows?service=wms
Showing a message telling: the following layers could not be loaded,please review those and reconfigure the QGIS project.
**1984 IGM Carta tecnica regionale 25k**
crs=EPSG:4326&dpiMode=7&format=image/png&layers=CTR_25k_IGM&styles&url=https://sit.cittametropolitana.na.it/geoserver/raster/ows&http-header:referer=

### Screenshots and GIFs
here is the screenshot with the error message on Android
error when loaded from local
![qfielderrorlocal](https://user-images.githubusercontent.com/132084725/235296274-d732d343-e521-430a-8c69-4c68824edfad.jpg)

error when loaded from cloud
![qfielderror](https://user-images.githubusercontent.com/132084725/235201827-97b2b59d-4f9e-4ac1-b418-a28fe5b71901.jpg)
.5

Here is a copy of the test project i created with 3 layers, Layer name="1984 IGM Carta tecnica regionale 25k" doesn't load on the Android version, while the other two do work.
[test.zip](https://github.com/opengisch/QField/files/11355472/test.zip)
.0 

### Desktop (please complete the following information)
 - OS: [Windows 10]
 - QGIS Version [3.28.3 Firenze ]
 - QFieldSync Version 

### Mobile (please complete the following information)
 - Device: [Xiaomi Mi 11 Lite 5G - MIUI 14.0]
 - OS: [Android 13 TKQ1 220829.002]
 - QField version: [2.7.6 (3313e4 v2.7.6]

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

[If the problem happened with QFieldCloud, please add your username and project name.]

Regards

Edit: added screenshot error message

**Comment by VxTedxV** [comment]
For my case, it works now (maybe after a recent update of QField or the WMS provider ?)

**Comment by nirvn** [comment]
@VxTedxV , good news; which version?

**Comment by VxTedxV** [comment]
QField 2.8.0 (333387) now

**Comment by nirvn** [comment]
@ItaliaMetal , can you confirm the issue is fixed in QField 2.8?

**Comment by ItaliaMetal** [comment]
> @ItaliaMetal , can you confirm the issue is fixed in QField 2.8?

 qfield version updated to 2.8.2, it is still not working.

**Comment by mcecilia-cl** [comment]
Still not working with version 2.8.3

**Comment by mrzh4s** [comment]
still not work on v3.0.2 but worked on iphone. but will force quit when zoom in or out.
