### ISSUE TITLE
QField on Windows doesn't Synchronize project from Cloud

### ISSUE THREAD

**Issue by Sekou225** [opengisch/QField#4411]
### Describe the issue
After installation of Qfield 2.81 on Windows PC, logging with my QFielCloud credentials, and downloading a project from QFieldCloud to local, everything works until there.

But when I finish editing my project on QGis Desktop 3.30 LTR and Synchronize it (through QFieldSync 4.5.0 plugin) on QFieldCloud, my QField 2.8.1 (Desktop) can't update the same QField Cloud project

### Reproduction steps
1. Open a QField Cloud project both in QGis and QField (desktop windows)
2. Edit the project in QGIS and save it
3. Synchronize the project with QFieldSync plugin as your local data replace online's one (Prefer Local buton --> Perform action buton) and wait for finishing
4. Then Open the same QField cloud project in the QField Desktop app
5. Hit MENU buton --> CLOUD buton --> Synchronize

### Expected behavior
The project must synchronize, download and apply the latest changes made in QGIS.

### Observed behavior
2 error messages say : 
     1. a network error has occured, please try again (when click on this message you will see appear : failed to copy some of the downloaded files on your device. Check your device storage)
     2. Project [project_name] failed to download (visible a couple of second)

### Screenshots and GIFs
[If applicable, add screenshots and GIFs to help explain your problem.]
![image](https://github.com/opengisch/QField/assets/91322749/2e183f33-d376-4732-95ca-158bf2c7ce4f)

### Desktop (please complete the following information)
 - OS: Windows 10 Enterprise 22H2 Build 19045.3086
 - QGIS Version 3.30 LTR
 - QFieldSync Version 4.5.0
 - QField 2.8.1 (Desktop App)

### Additional information
* Problem started happening recently, didn't happen in an older version of QField: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
* Problem happens with all files and projects, not only some files or projects: [Yes/No]

[If the problem happened with QFieldCloud, please add your username and project name.]

**Comment by SeqLaz** [comment]
We appreciate you bringing this issue to our attention. Your report will greatly assist us in addressing and resolving the problem.

Please be assured that our dedicated team of developers is actively working on fixing this issue.

If you have any additional questions or concerns, please don't hesitate to reach out to us. You can do so by clicking on the question mark in the right corner of the QFieldCloud platform. Our support team is always ready to assist you.

Best regards,

**Comment by Sekou225** [comment]
> Relaunching the applications and entering your credentials again:
> 
> 1. Check your internet connection: Ensure that you have a stable internet connection to access the QFieldCloud platform.
> 2. Update the app: Make sure you have the latest version of the QField app installed on your device. Updates often include bug fixes and improvements.
> 
> I will close this issue from the QField discussion, if the problem persists after performing these steps, please don't hesitate to contact our dedicated support team for further assistance. You can reach them by clicking on the question mark icon in the top-right corner of the QFieldCloud platform.

Hi @SeqLaz, thanks for your your retour. 
Solution you mention above don't work. I updated up my QField Desktop software from 2.8.1 to 2.8.4 (latest one) and still have this probleme. Many collaborators have the same problemes then we use different internet providers and environnement.
How we do to "BYPASS" this issu is that : 

1. Close the software by clicking twive on the cross on top of window, close also all others softwares that could use the files of the project you need to synchronize.
2. Run again the Qfield Software.
3. On the starting view, clic on QFieldCloud project without opening the project you want to sync.
4. Sign in if requested or wait for effective signing in
5. In project list, LONG PRESS ON the project you need to synchronize.
6. On the pop-up menu that appears, clic on Remove Stored Project
7. After that, clic again on the same project to download the last server's one with updates
8. Wait for the downloading and you’re ok.

What i think about the cause of this issus is that, while the Qfield is running and openned a project, it cant delete it, nor replace it's files by others beacause the files are in use by itself or an other Software (in my case it's QGIS). May this can help you improving QField for Desktop.

**Comment by elliec** [comment]
I have the same issue with a fully updated QGIS, QfieldSync, and Qfield Windows desktop. The workaround fixes it but it would be great if the sync worked as that set-up is really useful during development of forms. thanks!

**Comment by Mangoesmapping-GeorgeCorea** [comment]
I just also saw the same behaviour but it was as we were over quota. Just adding this here in case anyone is wondering why they see this message.

**Comment by Sekou225** [comment]
> I just also saw the same behaviour but it was as we were over quota. Just adding this here in case anyone is wondering why they see this message.

Hi,
Just to assure you that the problem is not from your quota. It is a such of programming concept error. What really happening when trying to sync is that :
 1- Your app connect to your server with you credentials, locate the project and the relative files.
 2- It initiate the dowmload
 3- It replace (OVERWRITE) your local old files, by their corresponding one that it just downloaded-
 4- The problem is that, it CAN NOT OVERWRITE files that are already opened (they are opened in Qfield itself cause you need to open your project before you can sync it). The same thing happen on windows when you try to remove or overwrite a file on windows while it is open in use by another application.

This is basically simple to fix. But for that, they need first to be aware of the problem.
Here they are quite to close issues whithout taking time to investigate. Pardon, mais c'est un constat.

**Comment by Sekou225** [comment]
Once again this issue still not resolved. If someone have something like a script or other corrective that can help to, PLEASE HELP US.
**THE BETTER FOR ME ACTUALLY IS A WAY TO MAKE SYNC AUTOMATIC !!!** 
please help

![image](https://github.com/opengisch/QField/assets/91322749/b28905c7-3268-4498-9abd-119e46a1e2a0)

**Comment by nirvn** [comment]
@Sekou225 , @elliec , I believe the issue has been addressed, could you confirm the fix has resolved your situation? You can download an installer containing the fix here: https://github.com/opengisch/QField/actions/runs/6987794548?pr=4806 (you'll need to be logged into your github account to see the file in the artifacts section of that page).

**Comment by Sekou225** [comment]
Hello all. Effectively the fix has resolve the probleme. Starting Qfield, an cmd window opens and start executing commands, same thing when SYNCHRONIZE button is pressed. 

I just installed the 3.0.7 version, but it still dont synchronizing. Other minor bugs on the 3.0.7 are still present, then we continue using the 2.8.3 version. 

Is there a way to apply this correctif to the 2.8.3 version?

Thanks in advance.

**Comment by nirvn** [comment]
@Sekou225 , the fix will be in 3.1, to be released soon, there are no plans to backport this to 2.8.

If you have other issues with 3.0, please file issues. QField 2.X is essentially retired.
